version: '3'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_vol:/data
    restart: always
    command: server /data --console-address ":9001"
    networks:
      - file  
  app:
    container_name: file_service
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ACCESS_KEY: minioadmin
      SECRET_KEY: minioadmin
      MINIO_URL: http://minio:9000
    command: bash -c 'gunicorn --bind 0.0.0.0:8003 main:app --worker-class uvicorn.workers.UvicornWorker --reload'
    networks:
      - file
volumes:
  minio_vol:
    name: minio_vol
networks:
  file:
    name: file
    driver: bridge
